- name: Ensure Prometheus config directory exists
  file:
    path: /opt/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
